language: java

jdk: openjdk15

sudo: false

script: mvn clean verify

before_install:
  - chmod +x mvnw

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: main